version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.staging
      args:
        - REACT_APP_API_URL=${STAGING_API_URL}
        - REACT_APP_JITSI_DOMAIN=${JITSI_DOMAIN}
    environment:
      - NODE_ENV=staging
    restart: unless-stopped
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.staging
    environment:
      - NODE_ENV=staging
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_staging_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_staging_data: 